### ISSUE TITLE
Please clarify version stability

### ISSUE THREAD

**Issue by remicollet** [awslabs/aws-crt-php#93]
According to https://pecl.php.net/package/awscrt

* 1.0.6, 1.07, 1.0.8 are "stable"
* 1.0.9 and 1.0.10 are "devel" which seems strange

Usually, when a stable version is released, next are also stable
and testing versions are released using "beta" or "RC" suffix

Can you please clarify ?

**Comment by remicollet** [comment]
Also, on github, only version up to 1.0.4 have tag:
https://github.com/awslabs/aws-crt-php/tags

**Comment by TingDaoK** [comment]
Non of those are really stable, we still have issue to build from PECL, we will fix the version issue after we fix the build.

**Comment by TingDaoK** [comment]
We are working on fixing the issue we currently have from `pecl install awscrt` and I don't really know what the best way to test.

Here is what I plan to do: 
- We will have all those 1.0.* as "devel" to test and make sure we fixed everything from `pecl install`. 
- We will publish `1.1.*` as "stable" afterward and make sure that the PECL package version line up with the github release.

If you know what's the proper way to test `pecl install` locally, or more gracefully instead of publishing to PECL, please let us know. I haven't really found anything from PECL guidance. 

BTW: If you, by any chance, can help us to apply for a PECL account as a PHP maintainer, it will be greatly helpful.

**Comment by remicollet** [comment]
> If you know what's the proper way to test pecl install locally, or more gracefully instead of publishing to PECL, please let us know. I haven't really found anything from PECL guidance.

`pecl install /path/to/foo-1.2.3.tgz`

> BTW: If you, by any chance, can help us to apply for a PECL account as a PHP maintainer, it will be greatly helpful.

Ask on pecl devel mailing list

**Comment by remicollet** [comment]
It looks like you are bitten by out of sources build

You have to use full paths defined as `$abs_builddir` and `$ext_srcdir`. `PHP_ADD_BUILD_DIR` may also be needed.

**Comment by TingDaoK** [comment]
https://github.com/awslabs/aws-crt-php/pull/90 
I have a work in progress fix here. And seems like we finally have it working. We will fix the version issue asap! Thanks

> Ask on pecl devel mailing list

I did, not get any response for over a month...

**Comment by remicollet** [comment]
> > Ask on pecl devel mailing list
> 
> I did, not get any response for over a month...

Perhaps @cmb69 may help for that

**Comment by TingDaoK** [comment]
Things were a bit off. But, we just released a new stable version 1.2.0, and it should be stable afterward. Thanks
